repo/quest_viewer/urls.py
from django.conf.urls import url

from quest_viewer import views

urlpatterns = [
		    url(r'^$', views.index, name='index'),
		    url(r'^discipline/(?P<discipline_id>\d+)$', views.discipline, name='discipline'),
		    url(r'^subject/(?P<subject_id>\d+)$', views.subject, name='subject')
		    ]

repo/repo/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import quest_viewer

urlpatterns = [
    # Examples:
    # url(r'^$', 'repo.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^v/', include('quest_viewer.urls', namespace='quest_viewer')),
]

repo/quest_viewer/models.py
from django.db import models
from django.utils.encoding import python_2_unicode_compatible

# TODO refactor and put it in a lib
def non_empty_str(s):
	return s != None and s != ''

# Generic comment, for whatever reason
@python_2_unicode_compatible
class Comment(models.Model):
	def __str__(self):
		return self.text
	text = models.TextField()

# The discipline, like Math
@python_2_unicode_compatible
class Discipline(models.Model):
	def __str__(self):
		return self.name
	name = models.CharField(max_length=100)
	comments = models.ManyToManyField(Comment,blank=True)

# The subject of a discipline, like Trigonometry
@python_2_unicode_compatible
class Subject(models.Model):
	def __str__(self):
		return self.name

	def full_description(self):
		ret = []
		ret.append(self.name)
		ret.append("Discipline: " + ','.join(self.main_disciplines_list()))
		if (self.super_subject != None):
			ret.append("Super-subject<" + str(self.super_subject) + ">")
		return ';'.join(ret)

	def main_disciplines_list(self):
		return [discipline_subj.discipline for discipline_subj in self.disciplinessubject_set.all() if discipline_subj.main_discipline]

	def main_disciplines_list_comma_separated(self, comma=', '):
		return comma.join([str(discipline) for discipline in self.main_disciplines_list()])
	main_disciplines_list_comma_separated.short_description = 'Main disciplines'

	name = models.CharField(max_length=100)
	disciplines = models.ManyToManyField(Discipline, through='DisciplinesSubject')
	super_subject = models.ForeignKey('self', null=True, default=None, blank=True)
	comments = models.ManyToManyField(Comment, blank=True)

@python_2_unicode_compatible
class DisciplinesSubject(models.Model):
	def __str__(self):
		return str(self.discipline) + ('(!)' if self.main_discipline else '') + ' - ' + str(self.subject)
	class Meta:
		unique_together = ('discipline', 'subject')
	discipline = models.ForeignKey(Discipline)
	subject = models.ForeignKey(Subject)
	main_discipline = models.BooleanField(default=False)

@python_2_unicode_compatible
class Institute(models.Model):
	def __str__(self):
		return self.name + ((';' + self.acronym) if non_empty_str(self.acronym) else '')
	name = models.CharField(max_length=1000)
	acronym = models.CharField(max_length=100,null=True, blank=True)
	comments = models.ManyToManyField(Comment, blank=True)

@python_2_unicode_compatible
class Source(models.Model):
	def __str__(self):
		return (self.institute.acronym if non_empty_str(self.institute.acronym) else self.institute.name) + (';' + str(self.year) if self.year != None else '')
	institute = models.ForeignKey(Institute)
	year = models.IntegerField(null=True, blank=True)
	comments = models.ManyToManyField(Comment, blank=True)
	class Meta:
		unique_together = ('institute','year')

class ImagesUrl(models.Model):
	url = models.CharField(max_length=1000)

class TextHTML(models.Model):
	text = models.TextField()
	images_url = models.ManyToManyField(ImagesUrl)

class TextTeX(models.Model):
	text = models.TextField()
	images_url = models.ManyToManyField(ImagesUrl)

class TextAlias(models.Model):
	textHTML = models.ForeignKey(TextHTML,null=True)
	textTeX = models.ForeignKey(TextTeX,null=True)

# A question in an exam
class Question(models.Model):
	question_text = models.ForeignKey(TextAlias)
	subjects = models.ManyToManyField(Subject,through='QuestionSubject')
	source = models.ForeignKey(Source)
	comments = models.ManyToManyField(Comment, blank=True)

class QuestionSubject(models.Model):
	question = models.ForeignKey(Question)
	subject = models.ForeignKey(Subject)
	main_subject = models.BooleanField(default=False)
	comments = models.ManyToManyField(Comment, blank=True)


class ObjectiveOptionItem(models.Model):
	identifier = models.CharField(max_length=3)
	item_text = models.ForeignKey(TextAlias)
	question = models.ForeignKey(Question)
	comments = models.ManyToManyField(Comment, blank=True)

# The same question may have some answers
class Answer(models.Model):
	answer_text = models.ForeignKey(TextAlias)
	question = models.ForeignKey(Question)
	comments = models.ManyToManyField(Comment, blank=True)
	

repo/quest_viewer/views.py
from django.shortcuts import render, get_object_or_404

from quest_viewer.models import *

def index(request):
	discipline_list = Discipline.objects.all()
	context = {'discipline_list': discipline_list}
	return render(request, 'quest_viewer/index.html', context)

def discipline(request,discipline_id):
	discipline = get_object_or_404(Discipline,pk=discipline_id)
	subject_list = discipline.subject_set.all()
	context = {'subject_list': subject_list,
			'discipline_id': discipline_id,
			'discipline': discipline}
	return render(request, 'quest_viewer/discipline.html', context)

def subject(request,subject_id):
	subject = get_object_or_404(Subject, pk=subject_id)
	discipline_list = subject.disciplinessubject_set.all()
	context = {'discipline_list': discipline_list,
			'subject_id': subject_id,
			'subject': subject}
	return render(request, 'quest_viewer/subject.html', context)

repo/quest_viewer/templates/quest_viewer/discipline.html
{% extends 'base.html' %}
{% block title %}Discipline {{ discipline }}{% endblock %}
{% block content %}
<h1><a href='{% url 'quest_viewer:discipline' discipline_id %}'>{{ discipline }}</a></h1>
{% if subject_list %}
	<ul>
		{% for subject in subject_list %}
			<li><a href='{% url 'quest_viewer:subject' subject.id %}'>{{ subject }}</a></li>
		{% endfor %}
	</ul>
{% else %}
	<p>No subjects for this discipline available</p>
{% endif %}
{% endblock %}

repo/quest_viewer/templates/quest_viewer/index.html
{% extends 'base.html' %}
{% block title %}Welcome to Exam Maker{% endblock %}
{% block content %}
{% if discipline_list %}
	<ul>
		{% for discipline in discipline_list %}
		<li><a href='{% url 'quest_viewer:discipline'  discipline.id %}'>{{ discipline }}</a></li>
		{% endfor %}
	</ul>
{% else %}
	<p>No disciplines available</p>
{% endif %}
{% endblock %}

repo/quest_viewer/templates/quest_viewer/subject.html
{% extends 'base.html' %}
{% block title %}Subject {{ subject }}{% endblock %}
{% block content %}
<h1><a href='{% url 'quest_viewer:subject' subject_id %}'>{{ subject }}</a></h1>
{% if discipline_list %}
	<ul>
		{% for d_subj in discipline_list %}
		<li> {% if d_subj.main_discipline %}!{% endif %}<a href='{% url 'quest_viewer:discipline'  d_subj.discipline.id %}'>{{ d_subj.discipline }}</a></li>
		{% endfor %}
	</ul>
{% else %}
	<p>No disciplines for this subject available</p>
{% endif %}
{% endblock %}

repo/templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		{# <link rel="stylesheet" href="style.css" /> #}
		<title>{% block title %}My amazing site{% endblock %}</title>
	</head>
	<body>
		<div id='navbar'>
			<a href='{% url 'quest_viewer:index' %}'>Home</a>
		</div>
		<div id='content'>
			{% block content %}{% endblock %}
		</div>
	</body>
</html>